[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_protocol = arduino
upload_port = COM5
upload_speed = 115200
build_src_filter =
    +<main.cpp>
    +<NutEngineRuntime.cpp>
    +<NanoNoHeap.cpp>
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit SSD1306 @ ^2.5.17
build_flags =
    -I../../src
    -I../../build/assets/nano
    -DNUT_FW_TAG=\"b36-demo\"
    -DNUT_CFG_MAX_OWNED_OBJECTS=3
    -DNUT_CFG_MAX_OBJECTS=3
    -DNUT_CFG_SCENE_LOADER_SCRATCH_BYTES=220

[env:nano_tunnel_run]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_protocol = arduino
upload_port = COM5
upload_speed = 115200
build_src_filter =
    +<main.cpp>
    +<NutEngineRuntime.cpp>
    +<NanoNoHeap.cpp>
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit SSD1306 @ ^2.5.17
build_flags =
    -I../../src
    -I../../build/assets/nano
    -DNUT_FW_TAG=\"b36-tunnel-run\"
    -DNUT_CFG_SCENE_LOADER_SCRATCH_BYTES=276
    -DNUT_CFG_MAX_CHILDREN_PER_OBJECT=4
    -DNUT_CFG_MAX_SCRIPTS_PER_OBJECT=1
    -DNUT_CFG_MAX_OWNED_OBJECTS=5
    -DNUT_CFG_MAX_OWNED_MESHES=1
    -DNUT_CFG_MAX_OWNED_SCRIPTS=2
    -DNUT_CFG_MAX_MESHES=1
    -DNUT_CFG_MAX_OBJECTS=5
    -DNUT_CFG_MAX_SCRIPT_RECORDS=2
    -DNUT_CFG_MAX_STRING_TABLE_BYTES=48
